### ISSUE TITLE
Authentications( Backend ) 

### ISSUE THREAD

**Issue by FranklinAGK** [BuildForSDG/Team-031#5]
**Auth**
- [x] Agree on a database type & format to use ( **noSQL(firebase) or SQL(postgres, MySQL, MongoDB)** ).
- [x] Account signup auth ( Framers & Sellers )
- [x] Login auth.
- [x] Reset password. 
- [x] Setup Push or Email notification ( oneSignal or Node.js ).

**Comment by Bascodes** [comment]
Setting up a mongo database can be pretty straightforward using mongoose. For log in authentication, i suggest using passport. It does all the salting and hashing and is ok too.  Can we just use express to serve our files?

**Comment by FranklinAGK** [comment]
thats left for @emekamartins @htolajide  to agree on, we are 2days late on our first sprint.
we need to before 8th of may so we can catch up.

**Comment by Bascodes** [comment]
ok. setting it up now

**Comment by htolajide** [comment]
@Bascodes what have you setup.? are we using mongodb atlas

**Comment by htolajide** [comment]
closed by mistake

**Comment by FranklinAGK** [comment]
@htolajide okay boss, what's the update?

**Comment by htolajide** [comment]
Yeah we can do farmer authentication, now. I want to deploy the app to heroku but my heroku acct is linked to my GitHub acct so I couldn't from buildForSDG GitHub.

Sent from Yahoo Mail on Android 
 
  On Thu, May 7, 2020 at 10:48 PM, Franklin Ejike<notifications@github.com> wrote:   


@htolajide okay boss, what's the update?

**Comment by FranklinAGK** [comment]
@htolajide let's just build locally first, we can worry about deploying our first prototype later

**Comment by htolajide** [comment]
Task completed
