### ISSUE TITLE
Features for customers ( Backend )

### ISSUE THREAD

**Issue by FranklinAGK** [BuildForSDG/Team-031#9]
- [x] Get the list of different product available for sale by sellers in users current location ( **eg: Tomatoes - #30, maze - #50 etc** ).
- [x] Retrieve the data of  sellers for a selected type of product ( **eg: when a user selects tomatoes, they should see the list of sellers for that particular product, and how much of the product they have, eg- 1000 pieces** )

**Comment by htolajide** [comment]
done
